"""initial schema

Revision ID: 7169a1fadba8
Revises: 
Create Date: 2026-03-23 13:57:37.254322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7169a1fadba8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('group_chat_name', sa.String(length=255), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_messages',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('sender_name', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('raw_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_messages_job_id'), 'extracted_messages', ['job_id'], unique=False)
    op.create_table('extracted_reels',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('reel_url', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('location_tag', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('owner_username', sa.String(length=255), nullable=True),
    sa.Column('extraction_status', sa.String(length=50), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('raw_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['extracted_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_reels_job_id'), 'extracted_reels', ['job_id'], unique=False)
    op.create_table('discovered_events',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('source_reel_id', sa.UUID(), nullable=True),
    sa.Column('google_maps_url', sa.Text(), nullable=True),
    sa.Column('google_calendar_url', sa.Text(), nullable=True),
    sa.Column('reddit_sentiment', sa.String(length=50), nullable=False),
    sa.Column('reddit_mention_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['extracted_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_reel_id'], ['extracted_reels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_events_job_id'), 'discovered_events', ['job_id'], unique=False)
    op.create_table('reddit_verifications',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('subreddit', sa.String(length=255), nullable=False),
    sa.Column('post_title', sa.Text(), nullable=False),
    sa.Column('post_url', sa.Text(), nullable=False),
    sa.Column('post_score', sa.Integer(), nullable=False),
    sa.Column('comment_snippet', sa.String(length=500), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('search_source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['discovered_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_verifications_event_id'), 'reddit_verifications', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reddit_verifications_event_id'), table_name='reddit_verifications')
    op.drop_table('reddit_verifications')
    op.drop_index(op.f('ix_discovered_events_job_id'), table_name='discovered_events')
    op.drop_table('discovered_events')
    op.drop_index(op.f('ix_extracted_reels_job_id'), table_name='extracted_reels')
    op.drop_table('extracted_reels')
    op.drop_index(op.f('ix_extracted_messages_job_id'), table_name='extracted_messages')
    op.drop_table('extracted_messages')
    op.drop_table('jobs')
    op.drop_table('sessions')
    # ### end Alembic commands ###
