"""add activities table

Revision ID: 809b2bd61899
Revises: ad2d7046bcf1
Create Date: 2026-03-27 12:06:58.490018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '809b2bd61899'
down_revision: Union[str, Sequence[str], None] = 'ad2d7046bcf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('who_suggested', sa.Text(), nullable=True),
    sa.Column('what_they_said', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('review_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('review_summary', sa.Text(), nullable=True),
    sa.Column('review_pros', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('review_cons', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('review_best_tip', sa.Text(), nullable=True),
    sa.Column('review_sources', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('booking_options', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_job_id'), 'activities', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_job_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
